name: Staging Deploy 

on:
  push:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TULSA_REMOTE_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Stop old versions
        run: ssh ubuntu@${{ secrets.SSH_HOST }} 'pm2 stop server; pm2 stop client;'
        
      - name: Deploy with rsync
        run: rsync -avz ./ ubuntu@${{ secrets.SSH_HOST }}:/apps/tulsa-remote-live/ --delete
        
      - name: Copy ENV file
        run: ssh ubuntu@${{ secrets.SSH_HOST }} 'cp /home/ubuntu/.env.staging /apps/tulsa-remote-live/server/.env'
        
      - name: Start Backend
        run: ssh ubuntu@${{ secrets.SSH_HOST }} 'cd /apps/tulsa-remote-live/server && npm install && nest build && pm2 start server'
        
      - name: Start Frontend
        run: ssh ubuntu@${{ secrets.SSH_HOST }} 'cd /apps/tulsa-remote-live/client && npm install && ng build --prod && pm2 start client'
        
